In [8]:
import numpy as np  #하나의 타입만 지원됨
x= np.array([3,1,2,"a"])
print(x)
print(type([3,1,2,"a"]))
print(type(x))
print(type([3,1,2]))

['3' '1' '2' 'a']
<class 'list'>
<class 'numpy.ndarray'>
<class 'list'>


In [14]:
c= [[1],[1,2]]
d=np.array([[1,1],[2,2]])
# for x,y in c: #c는 차원이 일치하지 않아 출력안됨
for x,y in d:
    print(x,y)

1 1
2 2


In [16]:
list3 = [1,3,5]
list4=[2,4]
print(list3 +list4)

[1, 3, 5, 2, 4]


In [17]:
#행열연산
x = np.array([1.0,2.0,3.0])
y = np.array([2.0,4.0,6.0])

print(x+y)
print(x-y)
print(x*y)
print(x/y)

[3. 6. 9.]
[-1. -2. -3.]
[ 2.  8. 18.]
[0.5 0.5 0.5]


In [21]:
print(x.shape)
print(x.dtype)
print(d.shape)
print(y/2.0)

(3,)
float64
(2, 2)
[1. 2. 3.]


In [22]:
print(x.ndim)

1


In [23]:
a = np.array([[1,2],[3,4],[5,6]]) #대괄호수
print(a.ndim)

2


In [24]:
print(a.shape) #대괄호안 대괄호

(3, 2)


In [25]:
a = np.array([[[1],[2]],[[3],[4]],[[5],[6]]])
print(a.ndim)

3


In [26]:
print(a.shape)

(3, 2, 1)


In [27]:
a = np.array([[[1,2],[2,2]],[[3,2],[4,2]],[[5,2],[6,2]]])
print(a.ndim)

3


In [28]:
print(a.shape)

(3, 2, 2)
