In [8]:
import numpy as np  #하나의 타입만 지원됨
x= np.array([3,1,2,"a"])
print(x)
print(type([3,1,2,"a"]))
print(type(x))
print(type([3,1,2]))

['3' '1' '2' 'a']
<class 'list'>
<class 'numpy.ndarray'>
<class 'list'>


In [14]:
c= [[1],[1,2]]
d=np.array([[1,1],[2,2]])
# for x,y in c: #c는 차원이 일치하지 않아 출력안됨
for x,y in d:
    print(x,y)

1 1
2 2


In [16]:
list3 = [1,3,5]
list4=[2,4]
print(list3 +list4)

[1, 3, 5, 2, 4]


In [17]:
#행열연산
x = np.array([1.0,2.0,3.0])
y = np.array([2.0,4.0,6.0])

print(x+y)
print(x-y)
print(x*y)
print(x/y)

[3. 6. 9.]
[-1. -2. -3.]
[ 2.  8. 18.]
[0.5 0.5 0.5]


In [21]:
print(x.shape)
print(x.dtype)
print(d.shape)
print(y/2.0)

(3,)
float64
(2, 2)
[1. 2. 3.]


In [22]:
print(x.ndim)

1


In [23]:
a = np.array([[1,2],[3,4],[5,6]]) #대괄호수
print(a.ndim)

2


In [24]:
print(a.shape) #대괄호안 대괄호

(3, 2)


In [25]:
a = np.array([[[1],[2]],[[3],[4]],[[5],[6]]])
print(a.ndim)

3


In [26]:
print(a.shape)

(3, 2, 1)


In [27]:
a = np.array([[[1,2],[2,2]],[[3,2],[4,2]],[[5,2],[6,2]]])
print(a.ndim)

3


In [29]:
print(a.shape)

(3, 2, 2)


In [30]:
np.dot(4,2)

8

In [32]:
ndar1 = np.array([3,2])
ndar2 = np.array([4,6])
np.dot(ndar1,ndar2)

24

In [33]:
ndar1 = np.array([[1,2],[3,4]])
ndar2 = np.array([[1,2],[3,4]])
np.dot(ndar1,ndar2)

array([[ 7, 10],
       [15, 22]])

In [36]:
ndar1 = np.array([[1,2],[3,4]])
ndar2 = np.array([[1,2],[3,4]])
np.matmul(ndar1,ndar1)

array([[ 7, 10],
       [15, 22]])

In [40]:
ndar2 = np.array([[[1],[2]],[[3],[4]]])
print(ndar2.shape)
print(ndar2.ndim)
a=ndar2.flatten()
print(ndar2)
print(a.ndim)

(2, 2, 1)
3
[[[1]
  [2]]

 [[3]
  [4]]]
1


In [41]:
ndarr= np.array([[1,2],[2,3],[3,4]])
ndarr.reshape(2,3)

array([[1, 2, 2],
       [3, 3, 4]])

In [47]:
ndarr.reshape(6,1)

array([[1],
       [2],
       [2],
       [3],
       [3],
       [4]])

In [56]:
np.random.randint(5,size=(2,4))

array([[0, 1, 3, 2],
       [4, 2, 0, 2]])

In [58]:
np.random.rand(2,3)

array([[0.62995783, 0.63949536, 0.72252354],
       [0.74631837, 0.95978175, 0.57833937]])

In [64]:
rng = np.random.default_rng()

In [67]:
rng.random()

0.18543230801443755

In [69]:
rng.integers(0,10,(2,4))

array([[7, 8, 1, 8],
       [2, 7, 3, 7]], dtype=int64)

In [71]:
ndarr = np.array([[6,3],[5,2],[4,1]])
ndarr > 4

array([[ True, False],
       [ True, False],
       [False, False]])

In [72]:
ndarr[ndarr>4]

array([6, 5])

In [78]:
ndarr[([[ True, True],
       [ True, True],
       [True, True]])]

array([6, 3, 5, 2, 4, 1])

In [79]:
ndarr[[[ True, True],
       [ True, True],
       [True, True]]]

array([6, 3, 5, 2, 4, 1])

In [81]:
ndarr[ndarr>1]

array([6, 3, 5, 2, 4])

In [82]:
ndarr[2:]

array([[4, 1]])