In [8]:
import numpy as np  #하나의 타입만 지원됨
x= np.array([3,1,2,"a"])
print(x)
print(type([3,1,2,"a"]))
print(type(x))
print(type([3,1,2]))

['3' '1' '2' 'a']
<class 'list'>
<class 'numpy.ndarray'>
<class 'list'>


In [14]:
c= [[1],[1,2]]
d=np.array([[1,1],[2,2]])
# for x,y in c: #c는 차원이 일치하지 않아 출력안됨
for x,y in d:
    print(x,y)

1 1
2 2


In [16]:
list3 = [1,3,5]
list4=[2,4]
print(list3 +list4)

[1, 3, 5, 2, 4]


In [17]:
#행열연산
x = np.array([1.0,2.0,3.0])
y = np.array([2.0,4.0,6.0])

print(x+y)
print(x-y)
print(x*y)
print(x/y)

[3. 6. 9.]
[-1. -2. -3.]
[ 2.  8. 18.]
[0.5 0.5 0.5]


In [21]:
print(x.shape)
print(x.dtype)
print(d.shape)
print(y/2.0)

(3,)
float64
(2, 2)
[1. 2. 3.]


In [22]:
print(x.ndim)

1


In [23]:
a = np.array([[1,2],[3,4],[5,6]]) #대괄호수
print(a.ndim)

2


In [24]:
print(a.shape) #대괄호안 대괄호

(3, 2)


In [25]:
a = np.array([[[1],[2]],[[3],[4]],[[5],[6]]])
print(a.ndim)

3


In [26]:
print(a.shape)

(3, 2, 1)


In [27]:
a = np.array([[[1,2],[2,2]],[[3,2],[4,2]],[[5,2],[6,2]]])
print(a.ndim)

3


In [29]:
print(a.shape)

(3, 2, 2)


In [30]:
np.dot(4,2)

8

In [32]:
ndar1 = np.array([3,2])
ndar2 = np.array([4,6])
np.dot(ndar1,ndar2)

24

In [33]:
ndar1 = np.array([[1,2],[3,4]])
ndar2 = np.array([[1,2],[3,4]])
np.dot(ndar1,ndar2)

array([[ 7, 10],
       [15, 22]])

In [36]:
ndar1 = np.array([[1,2],[3,4]])
ndar2 = np.array([[1,2],[3,4]])
np.matmul(ndar1,ndar1)

array([[ 7, 10],
       [15, 22]])

In [40]:
ndar2 = np.array([[[1],[2]],[[3],[4]]])
print(ndar2.shape)
print(ndar2.ndim)
a=ndar2.flatten()
print(ndar2)
print(a.ndim)

(2, 2, 1)
3
[[[1]
  [2]]

 [[3]
  [4]]]
1


In [41]:
ndarr= np.array([[1,2],[2,3],[3,4]])
ndarr.reshape(2,3)

array([[1, 2, 2],
       [3, 3, 4]])

In [47]:
ndarr.reshape(6,1)

array([[1],
       [2],
       [2],
       [3],
       [3],
       [4]])

In [56]:
np.random.randint(5,size=(2,4))

array([[0, 1, 3, 2],
       [4, 2, 0, 2]])

In [58]:
np.random.rand(2,3)

array([[0.62995783, 0.63949536, 0.72252354],
       [0.74631837, 0.95978175, 0.57833937]])

In [64]:
rng = np.random.default_rng()

In [67]:
rng.random()

0.18543230801443755

In [69]:
rng.integers(0,10,(2,4))

array([[7, 8, 1, 8],
       [2, 7, 3, 7]], dtype=int64)

In [71]:
ndarr = np.array([[6,3],[5,2],[4,1]])
ndarr > 4

array([[ True, False],
       [ True, False],
       [False, False]])

In [72]:
ndarr[ndarr>4]

array([6, 5])

In [78]:
ndarr[([[ True, True],
       [ True, True],
       [True, True]])]

array([6, 3, 5, 2, 4, 1])

In [79]:
ndarr[[[ True, True],
       [ True, True],
       [True, True]]]

array([6, 3, 5, 2, 4, 1])

In [81]:
ndarr[ndarr>1]

array([6, 3, 5, 2, 4])

In [83]:
ndarr[2:]

array([[4, 1]])

In [143]:
a= np.array([0]*10)
a1=np.zeros(10)
print(a)
print(a1)

a[4]=1
print(a)

b=np.arange(10,31)
print(b)

c=np.random.randint(0,size=(2,2))
print(c)

d=np.random.rand(2,4)
print(d)

[0 0 0 0 0 0 0 0 0 0]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 1 0 0 0 0 0]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]
[[70 84]
 [69 59]]
[[0.57261294 0.47491089 0.37357924 0.27706644]
 [0.73142874 0.43868666 0.40416739 0.63873066]]


In [160]:
rng = np.random.default_rng(1) 
# (seed값)에 숫자는 특정값이 고정되게 나오게함
# (null값)은 무작위 시드값이 나옴

In [159]:
ans = rng.integers(0,100,(2,2))
print(ans)

[[47 51]
 [75 95]]


In [200]:
e=np.arange(35,75)
print(e)
e6 = e.reshape(10,4)
print(e6)

e7 = e6[::-1]
print(e7)

e8= e6[1:9,2:4]
print(e8)

[35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58
 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74]
[[35 36 37 38]
 [39 40 41 42]
 [43 44 45 46]
 [47 48 49 50]
 [51 52 53 54]
 [55 56 57 58]
 [59 60 61 62]
 [63 64 65 66]
 [67 68 69 70]
 [71 72 73 74]]
[[71 72 73 74]
 [67 68 69 70]
 [63 64 65 66]
 [59 60 61 62]
 [55 56 57 58]
 [51 52 53 54]
 [47 48 49 50]
 [43 44 45 46]
 [39 40 41 42]
 [35 36 37 38]]
[[41 42]
 [45 46]
 [49 50]
 [53 54]
 [57 58]
 [61 62]
 [65 66]
 [69 70]]


In [221]:
e6

array([[35, 36, 37, 38],
       [39, 40, 41, 42],
       [43, 44, 45, 46],
       [47, 48, 49, 50],
       [51, 52, 53, 54],
       [55, 56, 57, 58],
       [59, 60, 61, 62],
       [63, 64, 65, 66],
       [67, 68, 69, 70],
       [71, 72, 73, 74]])

In [267]:
e9 = e6[:,-1]
print(e9)

e9_1=e6[:,-1:]
print(e9_1)

e10 = e9_1[::-1]
print(e10)

e10 = rng.integers(1,51,(5,6))
print(e10)
print(f"짝수만 출력 {e10[e10 % 2 == 0]}")


[38 42 46 50 54 58 62 66 70 74]
[[38]
 [42]
 [46]
 [50]
 [54]
 [58]
 [62]
 [66]
 [70]
 [74]]
[[74]
 [70]
 [66]
 [62]
 [58]
 [54]
 [50]
 [46]
 [42]
 [38]]
[[ 4 22 49  7 12 49]
 [ 3 35 27 42 46 18]
 [16 48 31 41  2 49]
 [22 10 33 24 37 20]
 [15 31 46 13 32  6]]
짝수만 출력 [ 4 22 12 42 46 18 16 48  2 22 10 24 20 46 32  6]


In [272]:
a = np.array([[1,2],[3,4]])



In [273]:
expanded = np.expand_dims(a,0)
print(expanded)
print(expanded.shape)

[[[1 2]
  [3 4]]]
(1, 2, 2)


In [274]:
expanded = np.expand_dims(a,1)
print(expanded)
print(expanded.shape)

[[[1 2]]

 [[3 4]]]
(2, 1, 2)


In [275]:
expanded = np.expand_dims(a,2)
print(expanded)
print(expanded.shape)

[[[1]
  [2]]

 [[3]
  [4]]]
(2, 2, 1)


In [277]:
np_ones = np.ones((1,2,1,3))
print(np_ones)
print(np_ones.shape)

[[[[1. 1. 1.]]

  [[1. 1. 1.]]]]
(1, 2, 1, 3)


In [279]:
sq =np.squeeze(np_ones)
print(sq)
print(sq.shape)

[[1. 1. 1.]
 [1. 1. 1.]]
(2, 3)


In [280]:
a= [1,2,2,3,3,3,4,4]

In [287]:
u_a,counts = np.unique(a,return_counts=True)
print(u_a)
print(counts)

[1 2 3 4]
[1 2 3 2]


In [299]:
u_a,counts,index = np.unique(a,return_index=True,return_counts=True)
print(u_a,counts,index)
print(index) # 0 1 3 6
print(counts)# 1 2 3 2


[1 2 3 4] [0 1 3 6] [1 2 3 2]
[1 2 3 2]
[0 1 3 6]


In [304]:
a = np.array([1,4,2,3])
b = np.sort(a)  #a[np.argsort(a)]랑 같음
print(f"a{a}")  
print(f"b{b}")  #숫자 크기대로
c=np.argsort(a) # 정렬됐을때 해당 원소의 위치 /한번 더 한다면 원상태로 돌릴수있다
print(f"c {c}")
print(f"cc {a[c]}")
# a.sort()
# print(f"a{a}")

a[1 4 2 3]
b[1 2 3 4]
c [0 2 3 1]


In [321]:
a = np.array([1,4,2,3])
np.mean(a)  #값들의 평균균
np.std(a)
np.var(a)
np.max(a)
np.min(a)
np.sum(a)
np.prod(a)
np.median(a)    #값들의 중앙값

2.5

In [314]:
np.std(a)

1.118033988749895

In [315]:
np.var(a)

1.25

In [316]:
np.max(a)

4

In [317]:
np.min(a)

1

In [318]:
np.sum(a)

10

In [319]:
np.prod(a)

24

In [320]:
np.median(a) 

2.5

In [323]:
x = np.arange(15, dtype=np.int64).reshape(3, 5)
x[1:, ::2] = -99

In [324]:
x

array([[  0,   1,   2,   3,   4],
       [-99,   6, -99,   8, -99],
       [-99,  11, -99,  13, -99]], dtype=int64)

In [325]:
a= np.sort(x,axis=0)
print(a)

[[-99   1 -99   3 -99]
 [-99   6 -99   8 -99]
 [  0  11   2  13   4]]


In [326]:
a= np.sort(x,axis=1)
print(a)

[[  0   1   2   3   4]
 [-99 -99 -99   6   8]
 [-99 -99 -99  11  13]]


In [395]:
a =np.array([1,1,2,3,4,5,5,5,5,7,8,9,10,11,24,100])

In [329]:
u_a=np.unique(a)
print(u_a)


[  1   2   3   4   5   7   8   9  10  11  24 100]


In [330]:
np.max(u_a)

100

In [331]:
np.min(u_a)

1

In [332]:
np.mean(u_a)

15.333333333333334

In [333]:
np.sum(u_a)

184

In [334]:
np.median(a)

5.0

In [342]:
x= np.arange(15,dtype=np.int64).reshape(3,5)
x[1:, ::2]=-99
print(x)

[[  0   1   2   3   4]
 [-99   6 -99   8 -99]
 [-99  11 -99  13 -99]]


In [389]:
a1 = x[:3,:1]
print(f"최대값 {np.max(a1)} 최소값 {np.min(a1)} 평균: {np.mean(a1)}")
a2=x[1:2]
print(f"2행의 합:{np.sum(a2)}")


최대값 0 최소값 -99 평균: -66.0
합:-283


In [404]:
a3 =np.argsort(a)
print(a3)
ans_a3 =(a[a3])
ans_a3[::-1]


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


array([100,  24,  11,  10,   9,   8,   7,   5,   5,   5,   5,   4,   3,
         2,   1,   1])